// This file is auto-generated by @hey-api/openapi-ts

export const EntryCreateRequestSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      examples: ["Entry Name"],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      examples: ["Markdown description."],
    },
    is_public: {
      type: "boolean",
      default: false,
    },
  },
  type: "object",
  required: ["name"],
} as const;

export const EntryDetailsResponseSchema = {
  properties: {
    response_model: {
      type: "string",
      default: "",
    },
    id: {
      type: "string",
      format: "uuid4",
      examples: ["6cfec811-c860-4727-a0ba-a6482b8d29cc"],
    },
    created_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    updated_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    name: {
      type: "string",
      maxLength: 255,
      examples: ["Entry Name"],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      examples: ["Markdown description."],
    },
    thumbnail_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      examples: ["URL for entry thumbnail preview"],
    },
    is_public: {
      type: "boolean",
    },
  },
  type: "object",
  required: ["id", "created_at", "updated_at", "name", "is_public"],
} as const;

export const EntryUpdateRequestSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      examples: ["Entry Name"],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      examples: ["Markdown description."],
    },
    is_public: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
    },
  },
  type: "object",
} as const;

export const PaginatedResponse_EntryDetailsResponse_Schema = {
  properties: {
    response_model: {
      type: "string",
      default: "",
    },
    current_page: {
      type: "integer",
      minimum: 1,
      default: 1,
    },
    per_page: {
      type: "integer",
      maximum: 100,
      minimum: 1,
      default: 100,
    },
    total_pages: {
      type: "integer",
    },
    total_items: {
      type: "integer",
    },
    items: {
      items: {
        $ref: "#/components/schemas/EntryDetailsResponse",
      },
      type: "array",
    },
  },
  type: "object",
  required: ["total_pages", "total_items", "items"],
} as const;

export const ShareLinkResponseSchema = {
  properties: {
    response_model: {
      type: "string",
      default: "",
    },
    id: {
      type: "string",
      format: "uuid4",
      examples: ["6cfec811-c860-4727-a0ba-a6482b8d29cc"],
    },
    created_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    updated_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    is_editable: {
      type: "boolean",
    },
    is_active: {
      type: "boolean",
    },
  },
  type: "object",
  required: ["id", "created_at", "updated_at", "is_editable", "is_active"],
} as const;

export const ShareLinkUpdateRequestSchema = {
  properties: {
    is_editable: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
    },
    is_active: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
    },
    msg: {
      type: "string",
    },
    type: {
      type: "string",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
} as const;

export const ViewCreateRequestSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      examples: ["View Name"],
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      examples: ["View Description"],
    },
    snapshot_json: {
      type: "string",
      format: "binary",
    },
    thumbnail_image: {
      anyOf: [
        {
          type: "string",
          format: "binary",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  required: ["name", "snapshot_json"],
} as const;

export const ViewResponseSchema = {
  properties: {
    response_model: {
      type: "string",
      default: "",
    },
    id: {
      type: "string",
      format: "uuid4",
      examples: ["6cfec811-c860-4727-a0ba-a6482b8d29cc"],
    },
    created_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    updated_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    name: {
      type: "string",
      maxLength: 255,
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    thumbnail_url: {
      type: "string",
      maxLength: 2083,
    },
    snapshot_url: {
      type: "string",
      maxLength: 2083,
    },
  },
  type: "object",
  required: [
    "id",
    "created_at",
    "updated_at",
    "name",
    "thumbnail_url",
    "snapshot_url",
  ],
} as const;

export const ViewUpdateRequestSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      examples: ["View Name"],
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      examples: ["View Description"],
    },
  },
  type: "object",
  required: ["name"],
} as const;
