// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zEntryCreateRequest = z.object({
  volseg_entry_id: z.string().uuid(),
  name: z.string().min(1).max(255),
  description: z.union([z.string(), z.null()]).optional(),
  is_public: z.union([z.boolean(), z.null()]).optional(),
});

export const zEntryDetailsResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.union([z.string(), z.null()]).optional(),
  is_public: z.boolean(),
  volseg_entry_id: z.string().uuid(),
});

export const zEntryUpdateRequest = z.object({
  name: z.union([z.string().max(255), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  is_public: z.union([z.boolean(), z.null()]).optional(),
});

export const zValidationError = z.object({
  loc: z.array(z.unknown()),
  msg: z.string(),
  type: z.string(),
});

export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

export const zPaginatedResponseEntryDetailsResponse = z.object({
  response_model: z.string().optional().default(""),
  page: z.number().int().gte(1),
  per_page: z.number().int().gte(1).lte(100),
  total_pages: z.number().int(),
  total_items: z.number().int(),
  items: z.array(zEntryDetailsResponse),
});

export const zShareLinkResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  is_editable: z.boolean(),
  is_active: z.boolean(),
});

export const zShareLinkUpdateRequest = z.object({
  is_editable: z.union([z.boolean(), z.null()]).optional(),
  is_active: z.union([z.boolean(), z.null()]).optional(),
});

export const zUploadFileRequest = z.object({
  file: z.string(),
});

export const zViewCreateRequest = z.object({
  name: z.string().max(255),
  description: z.union([z.string().max(255), z.null()]).optional(),
  snapshot_json: z.string(),
  thumbnail_image: z.union([z.string(), z.null()]).optional(),
});

export const zViewResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.union([z.string().max(2083), z.null()]),
  snapshot_url: z.string().max(2083),
});

export const zViewUpdateRequest = z.object({
  name: z.union([z.string().max(255), z.null()]).optional(),
  description: z.union([z.string().max(255), z.null()]).optional(),
});

export const zVolsegEntryResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  db_name: z.string().min(1).max(255),
  entry_id: z.string().min(1).max(255),
  is_public: z.boolean(),
});

export const zVolsegUploadEntry = z.object({
  db_name: z.string().min(1).max(255),
  entry_id: z.string().min(1).max(255),
  is_public: z.union([z.boolean(), z.null()]).optional(),
  annotations: z.string(),
  metadata: z.string(),
  data: z.string(),
});

export const zEntriesListPublicEntriesResponse =
  zPaginatedResponseEntryDetailsResponse;

export const zEntriesCreateEntryResponse = zEntryDetailsResponse;

export const zEntriesDeleteEntryResponse = z.string().uuid();

export const zEntriesGetEntryByIdResponse = zEntryDetailsResponse;

export const zEntriesUpdateEntryResponse = zEntryDetailsResponse;

export const zEntriesGetEntryByShareLinkResponse = zEntryDetailsResponse;

export const zEntriesGetEntryShareLinkResponse = zShareLinkResponse;

export const zViewsListViewsForEntryResponse = z.array(zViewResponse);

export const zViewsCreateViewResponse = zViewResponse;

export const zViewsDeleteViewResponse = z.string().uuid();

export const zViewsGetViewByIdResponse = zViewResponse;

export const zViewsUpdateViewResponse = zViewResponse;

export const zMeListEntriesForUserResponse =
  zPaginatedResponseEntryDetailsResponse;

export const zMeListVolsegEntriesForUserResponse =
  z.array(zVolsegEntryResponse);

export const zShareLinksGetShareLinkResponse = zShareLinkResponse;

export const zShareLinksUpdateShareLinkResponse = zShareLinkResponse;

export const zVolsegEntriesListPublicEntriesResponse =
  z.array(zVolsegEntryResponse);

export const zVolsegEntriesUploadEntryResponse = zVolsegEntryResponse;

export const zVolsegEntriesDeleteViewResponse = z.string().uuid();

export const zVolsegEntriesGetEntryByIdResponse = zVolsegEntryResponse;
