// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zEntryCreateRequest = z.object({
  name: z.string().min(1).max(255),
  description: z.union([z.string(), z.null()]).optional(),
  is_public: z.boolean().optional().default(false),
});

export const zEntryDetailsResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.union([z.string(), z.null()]).optional(),
  is_public: z.boolean(),
});

export const zEntryUpdateRequest = z.object({
  name: z.union([z.string().max(255), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  is_public: z.union([z.boolean(), z.null()]).optional(),
});

export const zValidationError = z.object({
  loc: z.array(z.unknown()),
  msg: z.string(),
  type: z.string(),
});

export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

export const zPaginatedResponseEntryDetailsResponse = z.object({
  response_model: z.string().optional().default(""),
  page: z.number().int().gte(1),
  per_page: z.number().int().gte(1).lte(100),
  total_pages: z.number().int(),
  total_items: z.number().int(),
  items: z.array(zEntryDetailsResponse),
});

export const zShareLinkResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  is_editable: z.boolean(),
  is_active: z.boolean(),
});

export const zShareLinkUpdateRequest = z.object({
  is_editable: z.union([z.boolean(), z.null()]).optional(),
  is_active: z.union([z.boolean(), z.null()]).optional(),
});

export const zViewCreateRequest = z.object({
  name: z.string().max(255),
  description: z.union([z.string().max(255), z.null()]).optional(),
  snapshot_json: z.string(),
  thumbnail_image: z.union([z.string(), z.null()]).optional(),
});

export const zViewResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.string().max(2083),
  snapshot_url: z.string().max(2083),
});

export const zViewUpdateRequest = z.object({
  name: z.string().max(255),
  description: z.union([z.string().max(255), z.null()]).optional(),
});

export const zEntriesListEntriesResponse =
  zPaginatedResponseEntryDetailsResponse;

export const zEntriesCreateEntryResponse = zEntryDetailsResponse;

export const zEntriesListEntriesForUserResponse =
  zPaginatedResponseEntryDetailsResponse;

export const zEntriesDeleteEntryResponse = z.string().uuid();

export const zEntriesGetEntryResponse = zEntryDetailsResponse;

export const zEntriesUpdateEntryResponse = zEntryDetailsResponse;

export const zEntriesGetEntryShareLinkResponse = zShareLinkResponse;

export const zEntriesGetEntryByShareLinkResponse = zEntryDetailsResponse;

export const zViewsListViewsForEntryResponse = z.array(zViewResponse);

export const zViewsCreateViewResponse = zViewResponse;

export const zViewsDeleteViewResponse = z.string().uuid();

export const zViewsGetViewResponse = zViewResponse;

export const zViewsUpdateViewResponse = zViewResponse;

export const zShareLinksGetShareLinkResponse = zShareLinkResponse;

export const zShareLinksUpdateShareLinkResponse = zShareLinkResponse;
