// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zEntryCreateRequest = z.object({
  name: z.string().min(1).max(255),
  description: z.union([z.string(), z.null()]).optional(),
  is_public: z.boolean().optional().default(false),
});

export const zEntryUpdateRequest = z.object({
  name: z.union([z.string().max(255), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  is_public: z.union([z.boolean(), z.null()]).optional(),
});

export const zValidationError = z.object({
  loc: z.array(z.unknown()),
  msg: z.string(),
  type: z.string(),
});

export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

export const zPrivateViewResponse = z.object({
  response_model: z.string().optional().default(""),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  id: z.string(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.union([z.string().max(2083), z.null()]).optional(),
  snapshot_url: z.union([z.string().max(2083), z.null()]).optional(),
});

export const zPrivateShareLinkResponse = z.object({
  id: z.string(),
  is_editable: z.boolean(),
  is_active: z.boolean(),
});

export const zPrivateEntryDetailsResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.union([z.string(), z.null()]).optional(),
  is_public: z.boolean(),
  views: z.array(zPrivateViewResponse),
  link: zPrivateShareLinkResponse,
});

export const zPaginatedResponsePrivateEntryDetailsResponse = z.object({
  current_page: z.number().int().gte(1).optional().default(1),
  per_page: z.number().int().gte(1).lte(100).optional().default(100),
  total_pages: z.number().int(),
  total_items: z.number().int(),
  items: z.array(zPrivateEntryDetailsResponse),
});

export const zPublicEntryPreviewResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.union([z.string(), z.null()]).optional(),
  is_public: z.boolean(),
});

export const zPaginatedResponsePublicEntryPreviewResponse = z.object({
  current_page: z.number().int().gte(1).optional().default(1),
  per_page: z.number().int().gte(1).lte(100).optional().default(100),
  total_pages: z.number().int(),
  total_items: z.number().int(),
  items: z.array(zPublicEntryPreviewResponse),
});

export const zPublicViewResponse = z.object({
  response_model: z.string().optional().default(""),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  id: z.string(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.union([z.string().max(2083), z.null()]).optional(),
  snapshot_url: z.union([z.string().max(2083), z.null()]).optional(),
});

export const zPublicEntryDetailsResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.union([z.string(), z.null()]).optional(),
  is_public: z.boolean(),
  views: z.array(zPublicViewResponse),
});

export const zShareLinkUpdateRequest = z.object({
  is_editable: z.union([z.boolean(), z.null()]).optional(),
  is_active: z.union([z.boolean(), z.null()]).optional(),
});

export const zViewCreateRequest = z.object({
  name: z.string().max(255),
  description: z.union([z.string().max(255), z.null()]).optional(),
  snapshot_json: z.string(),
  thumbnail_image: z.union([z.string(), z.null()]).optional(),
});

export const zViewResponse = z.object({
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  id: z.string(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.union([z.string().max(2083), z.null()]).optional(),
  snapshot_url: z.union([z.string().max(2083), z.null()]).optional(),
});

export const zViewUpdateRequest = z.object({
  name: z.string().max(255),
  description: z.union([z.string().max(255), z.null()]).optional(),
});

export const zEntriesListEntriesResponse =
  zPaginatedResponsePublicEntryPreviewResponse;

export const zEntriesCreateEntryResponse = zPrivateEntryDetailsResponse;

export const zEntriesListEntriesForUserResponse =
  zPaginatedResponsePrivateEntryDetailsResponse;

export const zEntriesDeleteEntryResponse = z.string().uuid();

export const zEntriesGetEntryResponse = z.union([
  zPrivateEntryDetailsResponse,
  zPublicEntryDetailsResponse,
]);

export const zEntriesUpdateEntryResponse = zPrivateEntryDetailsResponse;

export const zEntriesGetEntryByShareLinkResponse = z.union([
  zPrivateEntryDetailsResponse,
  zPublicEntryDetailsResponse,
]);

export const zViewsListViewsForEntryResponse = z.array(z.unknown());

export const zViewsCreateViewResponse = zPrivateViewResponse;

export const zViewsDeleteViewResponse = z.string().uuid();

export const zViewsGetViewResponse = z.union([
  zPrivateViewResponse,
  zPublicViewResponse,
]);

export const zViewsUpdateViewResponse = zViewResponse;

export const zShareLinksGetShareLinkResponse = zPrivateShareLinkResponse;

export const zShareLinksUpdateShareLinkResponse = zPrivateShareLinkResponse;
