erDiagram

    ENTRIES {
        int id PK

        string name
        string description
        string author_email
        string thumbnail_url

        datetime created_at
        datetime updated_at
        datetime deleted_at
    }

    PUBLIC_ENTRIES {
        int entry_id FK
    }

    VIEWS {
        int id PK
        int entry_id FK

        string title
        string description
        json mvsj

        datetime created_at
        datetime updated_at
        datetime deleted_at
    }

    SEGMENTATIONS {
        int id PK
        int volume_id FK
        string description
        string url
    }

    SEGMENTS {
        int id PK
        int segmentation_id FK
        string description
        string url
    }

    VOLUMES {
        int id PK
        int entry_id FK
        string description
        string url
    }

    ENTRIES ||--o{ VIEWS : ""
    ENTRIES }o--o| VOLUMES : ""
    VOLUMES ||--o{ SEGMENTATIONS : ""
    SEGMENTATIONS ||--o{ SEGMENTS : ""
    PUBLIC_ENTRIES ||--o{ ENTRIES : ""
