erDiagram

    USER {
        uuid id PK
        uuid openid PK
        str email
        boolean is_superuser

        datetime created_at
        datetime updated_at
        datetime deleted_at
    }

    ENTRIES {
        uuid id PK
        uuid user_id FK
        uuid link_id FK
        string name
        string description
        boolean is_public

        datetime created_at
        datetime updated_at
        datetime deleted_at
    }
    
    VIEWS {
        uuid id PK
        uuid entry_id FK
        string title
        string description
        str snapshot_uri
        str thumbnail_uri

        datetime created_at
        datetime updated_at
        datetime deleted_at
    }

    LINKS {
        uuid id PK
        uuid entry_id FK
        uuid link
        boolean editable

        datetime created_at
        datetime updated_at
        datetime deleted_at
    }
                
    USER ||--o{ ENTRIES : ""
    ENTRIES ||--o{ VIEWS : ""
    ENTRIES ||--|| LINKS : ""
