name: CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.5"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "server/pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev --project server

      - name: Run linter
        run: uv run --project server ruff check

      - name: Run formatting check
        run: uv run --project server ruff format --check